import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed": "#141b2b",
        "on-primary-container": "#e9e5ff",
        "surface-variant": "#dce2f3",
        "primary-fixed": "#e2dfff",
        "on-secondary": "#ffffff",
        "surface-container": "#e7eefe",
        "on-tertiary-fixed": "#191c1d",
        "on-secondary-container": "#5c6274",
        "on-background": "#151c27",
        "primary-container": "#5850ec",
        "primary": "#3e32d3",
        "inverse-surface": "#2a313d",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c5c7c8",
        "primary-fixed-dim": "#c3c0ff",
        "secondary": "#575e70",
        "surface-dim": "#d3daea",
        "tertiary-container": "#67696a",
        "tertiary": "#4e5152",
        "on-surface": "#151c27",
        "tertiary-fixed": "#e1e3e4",
        "surface-tint": "#4e44e2",
        "error-container": "#ffdad6",
        "on-surface-variant": "#464555",
        "on-primary-fixed": "#0f0069",
        "surface": "#f9f9ff",
        "secondary-fixed": "#dce2f7",
        "outline": "#777587",
        "on-primary-fixed-variant": "#3424ca",
        "outline-variant": "#c7c4d8",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#404758",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        "surface-container-high": "#e2e8f8",
        "secondary-container": "#d9dff5",
        "on-tertiary-container": "#e8e9ea",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "surface-container-highest": "#dce2f3",
        "secondary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed-variant": "#454748",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "sidebar": '#111827',
        "brand": '#5850ec',
        "brand_hover": '#4338ca',
        "text_main": '#1e293b',
        "text_muted": '#64748b'
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "260px",
        "section-margin": "32px",
        "element-stack": "12px",
        "container-padding": "24px",
        "grid-gutter": "20px",
        "card-gap": "20px"
      },
      fontFamily: {
        serif: ["Libre Caslon Text", "serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "sans": ["Plus Jakarta Sans", "Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
