export enum UserRole {
  SALES = 'SALES',
  ADMIN = 'ADMIN',
}

export enum SubscriptionState {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum SubscriptionPlan {
  STARTER = 'STARTER',
  PRO = 'PRO',
  ELITE = 'ELITE',
}

export enum ConversationState {
  OPEN = 'OPEN',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  WAITING_SELLER = 'WAITING_SELLER',
  HUMAN_ACTIVE = 'HUMAN_ACTIVE',
  AI_ACTIVE = 'AI_ACTIVE',
  ESCALATED = 'ESCALATED',
  ARCHIVED = 'ARCHIVED',
}

export enum AiMode {
  AI_ASSIST = 'AI_ASSIST',
  SMART_HYBRID = 'SMART_HYBRID',
  AUTO_REPLY = 'AUTO_REPLY',
  AI_OFF = 'AI_OFF',
}

export enum HeatTier {
  LOW = 'LOW',
  WARM = 'WARM',
  HOT = 'HOT',
  CRITICAL = 'CRITICAL',
}

export enum MessageSenderType {
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  AI = 'AI',
  SYSTEM = 'SYSTEM',
}

export enum MessageDeliveryState {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  DUE = 'DUE',
  OVERDUE = 'OVERDUE',
  COMPLETED = 'COMPLETED',
  SNOOZED = 'SNOOZED',
  CANCELLED = 'CANCELLED',
}

export enum FollowUpUrgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum RecipientStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  SUPPRESSED = 'SUPPRESSED',
  SKIPPED = 'SKIPPED',
}

export enum EscalationReason {
  CREDIT_SIMULATION_REQUEST = 'CREDIT_SIMULATION_REQUEST',
  PRICE_NEGOTIATION = 'PRICE_NEGOTIATION',
  SERIOUS_COMPLAINT = 'SERIOUS_COMPLAINT',
  AI_LOW_CONFIDENCE = 'AI_LOW_CONFIDENCE',
  UNKNOWN_INTENT = 'UNKNOWN_INTENT',
  FINANCIAL_CLAIM_BLOCKED = 'FINANCIAL_CLAIM_BLOCKED',
  MANUAL_TRIGGER = 'MANUAL_TRIGGER',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
  WA_CONNECTED = 'WA_CONNECTED',
  WA_DISCONNECTED = 'WA_DISCONNECTED',
  AI_MODE_CHANGED = 'AI_MODE_CHANGED',
  FOLLOW_UP_CREATED = 'FOLLOW_UP_CREATED',
  FOLLOW_UP_COMPLETED = 'FOLLOW_UP_COMPLETED',
  FOLLOW_UP_SNOOZED = 'FOLLOW_UP_SNOOZED',
  LEAD_HEAT_UPDATED = 'LEAD_HEAT_UPDATED',
  CAMPAIGN_CREATED = 'CAMPAIGN_CREATED',
  CAMPAIGN_APPROVED = 'CAMPAIGN_APPROVED',
  CAMPAIGN_CANCELLED = 'CAMPAIGN_CANCELLED',
  SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  QUOTA_TOPPED_UP = 'QUOTA_TOPPED_UP',
  SUPPRESSION_ADDED = 'SUPPRESSION_ADDED',
  SUPPRESSION_REMOVED = 'SUPPRESSION_REMOVED',
  DATA_EXPORTED = 'DATA_EXPORTED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
}

export enum WaSessionState {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  RECONNECTING = 'RECONNECTING',
  EXPIRED = 'EXPIRED',
}

export enum InvoiceStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
}

export enum ReferralStatus {
  SIGNED_UP = 'SIGNED_UP',
  TRIAL_ACTIVE = 'TRIAL_ACTIVE',
  CONVERTED_TO_PAID = 'CONVERTED_TO_PAID',
  EXPIRED = 'EXPIRED',
}

export enum QueueName {
  HOT_LEAD = 'HOT_LEAD',
  AI_REPLY = 'AI_REPLY',
  ESCALATION = 'ESCALATION',
  FOLLOW_UP = 'FOLLOW_UP',
  SUMMARY = 'SUMMARY',
  ANALYTICS = 'ANALYTICS',
  BLAST = 'BLAST',
}
